import { Check, Play, Search } from "lucide-react"
import { memo, useDeferredValue, useMemo, useState } from "react"
import { Button } from "../../../components/ui/button"
import { Input } from "../../../components/ui/input"
import type { ShotData } from "../../editor/constants/editorData.ts"

interface ShotBrowserViewProps { shots: ShotData[]; activeShotIndex: number; scopeShotIds?: string[]; notes: Record<string, { content: string; analysis: string }>; onLocateShot: (index: number) => void; onPlayShot: (index: number) => void; onSaveAndNext?: () => Promise<void>; queuePosition?: number; queueLength?: number; isResearchSaving?: boolean }

interface ShotRowProps { shot: ShotData; index: number; isActive: boolean; noteAnalysis: string; onLocateShot: (index: number) => void; onPlayShot: (index: number) => void }

const ShotRow = memo(function ShotRow({ shot, index, isActive, noteAnalysis, onLocateShot, onPlayShot }: ShotRowProps) {
  return <div style={{ contentVisibility: "auto", containIntrinsicSize: "0 48px" }} className={`flex items-center gap-3 border-b border-border px-4 py-3 ${isActive ? "bg-accent/10" : "hover:bg-bg-hover"}`}><button type="button" onClick={() => onLocateShot(index)} className="min-w-0 flex-1 text-left"><span className={`font-mono text-xs ${isActive ? "text-accent" : "text-text-muted"}`}>#{String(index + 1).padStart(2, "0")}</span><span className="ml-3 text-xs text-text-base">{shot.type || "未分析"}</span><span className="ml-3 font-mono text-[10px] text-text-muted">{shot.start.toFixed(2)}–{(shot.start + shot.duration).toFixed(2)} s</span>{noteAnalysis && <p className="mt-1 truncate text-xs text-text-muted">{noteAnalysis}</p>}</button><Button type="button" variant="ghost" size="icon-xs" aria-label={`播放镜头 ${index + 1}`} onClick={() => onPlayShot(index)} className="text-text-muted hover:text-accent"><Play className="size-3.5" /></Button></div>
}, (previous, next) => previous.shot === next.shot && previous.index === next.index && previous.isActive === next.isActive && previous.noteAnalysis === next.noteAnalysis)

export default function ShotBrowserView({ shots, activeShotIndex, scopeShotIds, notes, onLocateShot, onPlayShot, onSaveAndNext, queuePosition = activeShotIndex, queueLength = shots.length, isResearchSaving = false }: ShotBrowserViewProps) {
  const [query, setQuery] = useState("")
  const deferredQuery = useDeferredValue(query)
  const visible = useMemo(() => { const normalized = deferredQuery.trim().toLowerCase(); const allowed = scopeShotIds ? new Set(scopeShotIds) : null; return shots.map((shot, index) => ({ shot, index })).filter(({ shot, index }) => (!allowed || allowed.has(shot.id)) && (!normalized || `${index + 1} ${shot.type} ${notes[shot.id]?.content ?? ""} ${notes[shot.id]?.analysis ?? ""}`.toLowerCase().includes(normalized))) }, [deferredQuery, notes, scopeShotIds, shots])
  return <section className="flex min-h-0 min-w-0 flex-1 basis-1/2 flex-col overflow-hidden bg-bg"><div className="border-b border-border px-4 py-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><h2 className="text-sm font-medium text-text-base">研究队列</h2><p className="mt-1 text-xs text-text-muted">{scopeShotIds ? "当前研究范围内的相交镜头。" : "按真实镜号、用户笔记和镜头类型检索。"}</p></div><span className="shrink-0 font-mono text-xs text-text-muted">{visible.length}/{scopeShotIds?.length ?? shots.length}</span></div><div className="mt-3 flex flex-wrap items-center gap-2"><div className="relative min-w-48 flex-1"><Search className="pointer-events-none absolute left-2 top-1/2 size-3.5 -translate-y-1/2 text-text-muted" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索镜头或笔记" aria-label="搜索研究队列" className="h-8 border-border bg-bg-input pl-8 text-xs" /></div>{onSaveAndNext && <Button type="button" size="sm" onClick={() => void onSaveAndNext()} disabled={isResearchSaving || queuePosition >= queueLength - 1} className="gap-1.5"><Check className="size-3.5" />{isResearchSaving ? "保存中…" : `保存并下一镜 ${Math.min(queuePosition + 2, queueLength)}/${queueLength}`}</Button>}</div></div><div className="min-h-0 flex-1 overflow-y-auto">{!visible.length ? <p className="p-8 text-center text-sm text-text-muted">没有匹配的正式镜头。</p> : visible.map(({ shot, index }) => <ShotRow key={shot.id} shot={shot} index={index} isActive={activeShotIndex === index} noteAnalysis={notes[shot.id]?.analysis ?? ""} onLocateShot={onLocateShot} onPlayShot={onPlayShot} />)}</div></section>
}
