import { Play, Search } from "lucide-react"
import { useMemo, useState } from "react"
import { Button } from "../../../components/ui/button"
import { Input } from "../../../components/ui/input"
import type { ShotData } from "../../editor/constants/editorData.ts"

interface ShotBrowserViewProps { shots: ShotData[]; activeShotIndex: number; notes: Record<string, { content: string; analysis: string }>; onLocateShot: (index: number) => void; onPlayShot: (index: number) => void }

export default function ShotBrowserView({ shots, activeShotIndex, notes, onLocateShot, onPlayShot }: ShotBrowserViewProps) {
  const [query, setQuery] = useState("")
  const visible = useMemo(() => { const normalized = query.trim().toLowerCase(); return shots.map((shot, index) => ({ shot, index })).filter(({ shot, index }) => !normalized || `${index + 1} ${shot.type} ${notes[shot.id]?.content ?? ""} ${notes[shot.id]?.analysis ?? ""}`.toLowerCase().includes(normalized)) }, [notes, query, shots])
  return <section className="flex min-h-0 flex-1 flex-col overflow-hidden bg-bg"><div className="border-b border-border px-4 py-3"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-medium text-text-base">全片镜头 Browser</h2><p className="mt-1 text-xs text-text-muted">按真实镜号、用户笔记和镜头类型检索。</p></div><span className="font-mono text-xs text-text-muted">{visible.length}/{shots.length}</span></div><div className="relative mt-3 max-w-md"><Search className="pointer-events-none absolute left-2 top-1/2 size-3.5 -translate-y-1/2 text-text-muted" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索镜头或笔记" aria-label="搜索全片镜头" className="h-8 border-border bg-bg-input pl-8 text-xs" /></div></div><div className="min-h-0 flex-1 overflow-y-auto">{!visible.length ? <p className="p-8 text-center text-sm text-text-muted">没有匹配的正式镜头。</p> : visible.map(({ shot, index }) => <div key={shot.id} className={`flex items-center gap-3 border-b border-border px-4 py-3 ${activeShotIndex === index ? "bg-accent/10" : "hover:bg-bg-hover"}`}><button type="button" onClick={() => onLocateShot(index)} className="min-w-0 flex-1 text-left"><span className={`font-mono text-xs ${activeShotIndex === index ? "text-accent" : "text-text-muted"}`}>#{String(index + 1).padStart(2, "0")}</span><span className="ml-3 text-xs text-text-base">{shot.type || "未分析"}</span><span className="ml-3 font-mono text-[10px] text-text-muted">{shot.start.toFixed(2)}–{(shot.start + shot.duration).toFixed(2)} s</span>{notes[shot.id]?.analysis && <p className="mt-1 truncate text-xs text-text-muted">{notes[shot.id].analysis}</p>}</button><Button type="button" variant="ghost" size="icon-xs" aria-label={`播放镜头 ${index + 1}`} onClick={() => onPlayShot(index)} className="text-text-muted hover:text-accent"><Play className="size-3.5" /></Button></div>)}</div></section>
}
