import { ArrowUpRight, Circle, Grid3X3, Minus, MousePointer2, Redo2, Spline, Square, Trash2, Triangle, Undo2 } from "lucide-react";
import type { CSSProperties } from "react";
import { Button } from "../../../components/ui/button";
import { Checkbox } from "../../../components/ui/checkbox";
import type { CompositionDrawingTool, CompositionGuideId, CompositionOverlaySettings } from "../types";
import { DEFAULT_COMPOSITION_OVERLAY_SETTINGS } from "../types";

interface CompositionOverlayPanelProps {
  settings: CompositionOverlaySettings;
  drawingTool: CompositionDrawingTool;
  selectedShapeId: string | null;
  onChange: (settings: CompositionOverlaySettings) => void;
  onDeleteSelectedShape: () => void;
  onUndoShapes: () => void;
  onRedoShapes: () => void;
  canUndoShapes: boolean;
  canRedoShapes: boolean;
  onDrawingToolChange: (tool: CompositionDrawingTool) => void;
  onSelectedShapeChange: (shapeId: string | null) => void;
}

const guides: Array<{ id: CompositionGuideId; label: string }> = [
  { id: "none", label: "关闭" }, { id: "thirds", label: "三分法" }, { id: "center", label: "中心十字" }, { id: "diagonal", label: "对角线" },
  { id: "horizontal-thirds", label: "水平三等分" }, { id: "vertical-thirds", label: "垂直三等分" }, { id: "grid", label: "自定义网格" }, { id: "golden-ratio", label: "黄金分割" },
];
const colors = ["#ffffff", "#111827", "#3b82f6", "#f59e0b", "#ef4444", "#22c55e"];
const drawingTools: Array<{ id: CompositionDrawingTool; label: string; icon: typeof MousePointer2 }> = [
  { id: "select", label: "选择", icon: MousePointer2 }, { id: "line", label: "直线", icon: Minus }, { id: "rectangle", label: "矩形", icon: Square }, { id: "ellipse", label: "椭圆", icon: Circle }, { id: "triangle", label: "三角形", icon: Triangle }, { id: "arrow", label: "箭头", icon: ArrowUpRight }, { id: "curve", label: "曲线", icon: Spline },
];

export default function CompositionOverlayPanel({ settings, drawingTool, selectedShapeId, onChange, onDeleteSelectedShape, onUndoShapes, onRedoShapes, canUndoShapes, canRedoShapes, onDrawingToolChange, onSelectedShapeChange }: CompositionOverlayPanelProps) {
  const update = (patch: Partial<CompositionOverlaySettings>) => onChange({ ...settings, ...patch });
  return <section className="flex flex-col gap-3 border-t border-border pb-3 pt-3">
    <div className="flex items-center justify-between gap-3"><p className="font-mono editor-heading tracking-wider text-text-muted">构图蒙版</p><button type="button" role="switch" aria-checked={settings.enabled} aria-label="显示构图蒙版" onClick={() => update({ enabled: !settings.enabled })} className={`relative h-[18px] w-8 shrink-0 overflow-hidden rounded-full transition-colors ${settings.enabled ? "bg-accent" : "bg-white/15"}`}><span className={`absolute left-0.5 top-0.5 size-3.5 rounded-full bg-white shadow-sm transition-transform ${settings.enabled ? "translate-x-3.5" : "translate-x-0"}`} /></button></div>
    {settings.enabled && <>
    <label className="flex cursor-pointer items-center gap-2 border-t border-border pt-3"><Checkbox checked={settings.includeInScreenshots} aria-label="截图带构图" onCheckedChange={(checked) => update({ includeInScreenshots: checked })} /><span className="font-mono editor-heading tracking-wider text-text-muted">截图带构图</span></label>
    <div><p className="mb-2 font-mono editor-heading tracking-wider text-text-muted">构图辅助</p><div className="grid grid-cols-2 gap-1.5">{guides.map((guide) => <Button key={guide.id} type="button" variant="outline" size="sm" aria-pressed={settings.guide === guide.id} onClick={() => update({ guide: guide.id })} className={settings.guide === guide.id ? "h-7 gap-1 px-2 editor-body font-normal border-accent/50 bg-accent/15 text-accent hover:bg-accent/20 hover:text-accent" : "h-7 gap-1 px-2 editor-body font-normal border-border text-text-muted hover:text-white"}>{guide.id === "grid" && <Grid3X3 className="size-3" />}{guide.label}</Button>)}</div></div>
    {settings.guide === "grid" && <div className="grid grid-cols-2 gap-2 border-t border-border pt-3"><label className="editor-meta text-text-muted">行数<input type="number" min="1" max="12" value={settings.gridRows} onChange={(event) => update({ gridRows: Math.max(1, Math.min(12, Number(event.target.value) || 1)) })} className="editor-number mt-1 h-7 w-full rounded border border-border bg-bg-input px-2 font-mono editor-body text-white" /></label><label className="editor-meta text-text-muted">列数<input type="number" min="1" max="12" value={settings.gridColumns} onChange={(event) => update({ gridColumns: Math.max(1, Math.min(12, Number(event.target.value) || 1)) })} className="editor-number mt-1 h-7 w-full rounded border border-border bg-bg-input px-2 font-mono editor-body text-white" /></label></div>}
    <div className="border-t border-border pt-3"><div className="mb-2 flex items-center justify-between"><p className="font-mono editor-heading tracking-wider text-text-muted">绘制</p><div className="flex gap-1"><Button type="button" variant="ghost" size="icon-xs" title="撤销" aria-label="撤销" disabled={!canUndoShapes} onClick={onUndoShapes}><Undo2 /></Button><Button type="button" variant="ghost" size="icon-xs" title="重做" aria-label="重做" disabled={!canRedoShapes} onClick={onRedoShapes}><Redo2 /></Button></div></div><div className="grid grid-cols-4 gap-1">{drawingTools.map((tool) => { const Icon = tool.icon; return <Button key={tool.id} type="button" variant="outline" size="icon-sm" title={tool.label} aria-label={tool.label} aria-pressed={drawingTool === tool.id} onClick={() => onDrawingToolChange(tool.id)} className={drawingTool === tool.id ? "size-6 border-accent/50 bg-accent/15 text-accent hover:bg-accent/20 hover:text-accent" : "size-6 border-border text-text-muted hover:text-white"}><Icon className="size-3" /></Button>; })}</div>{selectedShapeId && <Button type="button" variant="outline" size="sm" onClick={onDeleteSelectedShape} className="mt-2 h-7 w-full editor-body font-normal border-red-500/30 text-red-300 hover:border-red-500/50 hover:bg-red-500/10 hover:text-red-200"><Trash2 className="size-3" />删除选中图形</Button>}</div>
    <div className="border-t border-border pt-3"><p className="mb-2 font-mono editor-heading tracking-wider text-text-muted">安全区</p><Button type="button" variant="outline" size="sm" aria-pressed={settings.showSafeMargins} onClick={() => update({ showSafeMargins: !settings.showSafeMargins })} className={`h-7 w-full editor-body font-normal ${settings.showSafeMargins ? "border-accent/50 bg-accent/15 text-accent hover:bg-accent/20 hover:text-accent" : "border-border text-text-muted hover:text-white"}`}>动作 5% · 标题 10%</Button></div>
    <div className="border-t border-border pt-3"><p className="mb-2 font-mono editor-heading tracking-wider text-text-muted">样式</p><div className="flex items-center gap-1.5">{colors.map((color) => <button key={color} type="button" aria-label={`辅助线颜色 ${color}`} onClick={() => update({ color })} className={`size-5 rounded-full border-2 ${settings.color === color ? "border-accent scale-110" : "border-white/25"}`} style={{ backgroundColor: color }} />)}</div><label className="mt-3 block editor-meta text-text-muted">透明度 <span className="font-mono text-text-dim">{Math.round(settings.opacity * 100)}%</span><input type="range" min="0.15" max="1" step="0.05" value={settings.opacity} onChange={(event) => update({ opacity: Number(event.target.value) })} className="editor-range mt-1" style={{ "--editor-range-progress": `${((settings.opacity - 0.15) / 0.85) * 100}%` } as CSSProperties} /></label><div className="mt-2 grid grid-cols-2 gap-1.5"><Button type="button" variant="outline" size="sm" aria-pressed={settings.lineStyle === "solid"} onClick={() => update({ lineStyle: "solid" })} className={settings.lineStyle === "solid" ? "h-7 editor-body font-normal border-accent/50 bg-accent/15 text-accent hover:text-accent" : "h-7 editor-body font-normal border-border text-text-muted hover:text-white"}>实线</Button><Button type="button" variant="outline" size="sm" aria-pressed={settings.lineStyle === "dashed"} onClick={() => update({ lineStyle: "dashed" })} className={settings.lineStyle === "dashed" ? "h-7 editor-body font-normal border-accent/50 bg-accent/15 text-accent hover:text-accent" : "h-7 editor-body font-normal border-border text-text-muted hover:text-white"}>虚线</Button></div><div className="mt-2 grid grid-cols-3 gap-1.5">{([1, 2, 3] as const).map((lineWidth) => <Button key={lineWidth} type="button" variant="outline" size="sm" aria-pressed={settings.lineWidth === lineWidth} onClick={() => update({ lineWidth })} className={settings.lineWidth === lineWidth ? "h-7 editor-body font-normal border-accent/50 bg-accent/15 text-accent hover:text-accent" : "h-7 editor-body font-normal border-border text-text-muted hover:text-white"}>{lineWidth === 1 ? "细" : lineWidth === 2 ? "中" : "粗"}</Button>)}</div></div>
    <Button type="button" variant="outline" size="sm" onClick={() => { onChange({ ...DEFAULT_COMPOSITION_OVERLAY_SETTINGS, enabled: settings.enabled }); onDrawingToolChange("select"); onSelectedShapeChange(null); }} className="h-7 editor-body font-normal border-red-500/30 text-red-300 hover:border-red-500/50 hover:bg-red-500/10 hover:text-red-200"><Trash2 className="size-3" />清除蒙版</Button>
    </>}
  </section>;
}
