#include "aisenshot/checkpoint.h"

#include <cstddef>

namespace aisenshot {
namespace {

constexpr std::uint32_t kMagic = 0x41534350U;
constexpr std::uint32_t kMaxAnalysisSamples = 16'777'216U;
constexpr std::uint32_t kMaxCheckpointBytes = 128U * 1024U * 1024U;

void append_u32(std::vector<std::uint8_t>& out, std::uint32_t value) { for (int i = 0; i < 4; ++i) out.push_back(static_cast<std::uint8_t>(value >> (i * 8))); }
void append_u64(std::vector<std::uint8_t>& out, std::uint64_t value) { for (int i = 0; i < 8; ++i) out.push_back(static_cast<std::uint8_t>(value >> (i * 8))); }
void append_i64(std::vector<std::uint8_t>& out, std::int64_t value) { append_u64(out, static_cast<std::uint64_t>(value)); }
void append_i32(std::vector<std::uint8_t>& out, std::int32_t value) { append_u32(out, static_cast<std::uint32_t>(value)); }
void append_bool(std::vector<std::uint8_t>& out, bool value) { out.push_back(value ? 1U : 0U); }
void append_bytes(std::vector<std::uint8_t>& out, const std::vector<std::uint8_t>& bytes) { append_u32(out, static_cast<std::uint32_t>(bytes.size())); out.insert(out.end(), bytes.begin(), bytes.end()); }

bool read_u32(const std::vector<std::uint8_t>& in, std::size_t* offset, std::uint32_t* value) { if (!offset || !value || *offset > in.size() || in.size() - *offset < 4) return false; *value = 0; for (int i = 0; i < 4; ++i) *value |= static_cast<std::uint32_t>(in[*offset + i]) << (i * 8); *offset += 4; return true; }
bool read_u64(const std::vector<std::uint8_t>& in, std::size_t* offset, std::uint64_t* value) { if (!offset || !value || *offset > in.size() || in.size() - *offset < 8) return false; *value = 0; for (int i = 0; i < 8; ++i) *value |= static_cast<std::uint64_t>(in[*offset + i]) << (i * 8); *offset += 8; return true; }
bool read_i64(const std::vector<std::uint8_t>& in, std::size_t* offset, std::int64_t* value) { std::uint64_t raw = 0; if (!read_u64(in, offset, &raw)) return false; *value = static_cast<std::int64_t>(raw); return true; }
bool read_i32(const std::vector<std::uint8_t>& in, std::size_t* offset, std::int32_t* value) { std::uint32_t raw = 0; if (!read_u32(in, offset, &raw)) return false; *value = static_cast<std::int32_t>(raw); return true; }
bool read_bool(const std::vector<std::uint8_t>& in, std::size_t* offset, bool* value) { if (!offset || !value || *offset >= in.size() || (in[*offset] != 0 && in[*offset] != 1)) return false; *value = in[*offset] != 0; ++*offset; return true; }
bool read_bytes(const std::vector<std::uint8_t>& in, std::size_t* offset, std::vector<std::uint8_t>* bytes) { std::uint32_t length = 0; if (!read_u32(in, offset, &length) || length > kMaxAnalysisSamples || *offset > in.size() || in.size() - *offset < length) return false; bytes->assign(in.begin() + static_cast<std::ptrdiff_t>(*offset), in.begin() + static_cast<std::ptrdiff_t>(*offset + length)); *offset += length; return true; }
void append_event(std::vector<std::uint8_t>& out, const SceneEvent& event) { append_u32(out, static_cast<std::uint32_t>(event.type)); append_i64(out, event.timestamp_us); append_u64(out, event.presentation_index); append_i32(out, event.score_q); append_i32(out, event.threshold_q); append_i32(out, event.delta_luma_q); append_i32(out, event.delta_hue_q); append_i32(out, event.delta_saturation_q); append_i64(out, event.transition_start_us); append_i64(out, event.transition_end_us); append_i64(out, event.boundary_timestamp_us); append_u32(out, event.direction); append_u32(out, event.source); }
bool read_event(const std::vector<std::uint8_t>& in, std::size_t* offset, SceneEvent* event) { std::uint32_t type = 0, direction = 0, source = 0; if (!event || !read_u32(in, offset, &type) || type > static_cast<std::uint32_t>(SceneEventType::Fade) || !read_i64(in, offset, &event->timestamp_us) || !read_u64(in, offset, &event->presentation_index) || !read_i32(in, offset, &event->score_q) || !read_i32(in, offset, &event->threshold_q) || !read_i32(in, offset, &event->delta_luma_q) || !read_i32(in, offset, &event->delta_hue_q) || !read_i32(in, offset, &event->delta_saturation_q) || !read_i64(in, offset, &event->transition_start_us) || !read_i64(in, offset, &event->transition_end_us) || !read_i64(in, offset, &event->boundary_timestamp_us) || !read_u32(in, offset, &direction) || !read_u32(in, offset, &source) || direction > 255 || source > 255) return false; event->type = static_cast<SceneEventType>(type); event->direction = static_cast<std::uint8_t>(direction); event->source = static_cast<std::uint8_t>(source); return true; }

}  // namespace

bool serialize_checkpoint(const CheckpointState& state, std::vector<std::uint8_t>* output, ErrorCode* error) {
  if (!output || !error || state.schema_version != 1 || state.engine_state_version == 0 || state.previous_metrics.luma_plane.size() > kMaxAnalysisSamples || state.previous_metrics.luma_plane.size() != state.previous_metrics.hue_plane.size() || state.previous_metrics.luma_plane.size() != state.previous_metrics.saturation_plane.size() || state.adaptive.window.size() > 120 || state.resolved_history.size() > 1'000'000 || state.delivered_event_count > state.resolved_history.size()) { if (error) *error = ErrorCode::InvalidCheckpoint; return false; }
  output->clear(); output->reserve(256 + state.previous_metrics.luma_plane.size() * 3);
  append_u32(*output, kMagic); append_u32(*output, state.schema_version); append_u32(*output, state.engine_state_version); append_u64(*output, state.config_hash); append_i64(*output, state.last_timestamp_us); append_u64(*output, state.last_presentation_index); append_bool(*output, state.has_frame); append_bool(*output, state.flushed);
  append_u32(*output, state.previous_metrics.sample_width); append_u32(*output, state.previous_metrics.sample_height); append_bool(*output, state.previous_metrics.has_previous); append_i32(*output, state.previous_metrics.mean_luma_q); append_i32(*output, state.previous_metrics.delta_luma_q); append_i32(*output, state.previous_metrics.delta_hue_q); append_i32(*output, state.previous_metrics.delta_saturation_q); append_i32(*output, state.previous_metrics.content_score_q); append_bytes(*output, state.previous_metrics.luma_plane); append_bytes(*output, state.previous_metrics.hue_plane); append_bytes(*output, state.previous_metrics.saturation_plane);
  append_bool(*output, state.content.has_event); append_i64(*output, state.content.last_event_timestamp_us); append_u32(*output, static_cast<std::uint32_t>(state.adaptive.window.size()));
  for (const auto& entry : state.adaptive.window) { append_i32(*output, entry.score_q); append_i64(*output, entry.timestamp_us); append_u64(*output, entry.presentation_index); append_i32(*output, entry.delta_luma_q); append_i32(*output, entry.delta_hue_q); append_i32(*output, entry.delta_saturation_q); }
  append_u64(*output, state.adaptive.last_emitted_index); append_bool(*output, state.adaptive.has_emitted); append_i64(*output, state.adaptive.last_event_timestamp_us); append_bool(*output, state.threshold.processed); append_bool(*output, state.threshold.fade_out); append_i64(*output, state.threshold.fade_start_us); append_u64(*output, state.threshold.fade_start_index); append_i64(*output, state.threshold.last_scene_cut_us); append_i64(*output, state.threshold.last_timestamp_us); append_u32(*output, static_cast<std::uint32_t>(state.resolved_history.size())); append_u64(*output, state.delivered_event_count); for (const auto& resolved : state.resolved_history) { append_event(*output, resolved.event); append_u32(*output, resolved.source_mask); }
  if (output->size() > kMaxCheckpointBytes) { output->clear(); *error = ErrorCode::InvalidCheckpoint; return false; } *error = ErrorCode::None; return true;
}

bool deserialize_checkpoint(const std::vector<std::uint8_t>& input, std::uint64_t expected_config_hash, std::uint32_t expected_engine_state_version, CheckpointState* output, ErrorCode* error) {
  if (!output || !error || input.size() > kMaxCheckpointBytes) { if (error) *error = ErrorCode::InvalidCheckpoint; return false; }
  std::size_t offset = 0; std::uint32_t magic = 0, sample_width = 0, sample_height = 0, window_size = 0, history_size = 0; CheckpointState candidate{};
  if (!read_u32(input, &offset, &magic) || magic != kMagic || !read_u32(input, &offset, &candidate.schema_version) || !read_u32(input, &offset, &candidate.engine_state_version) || !read_u64(input, &offset, &candidate.config_hash) || !read_i64(input, &offset, &candidate.last_timestamp_us) || !read_u64(input, &offset, &candidate.last_presentation_index) || !read_bool(input, &offset, &candidate.has_frame) || !read_bool(input, &offset, &candidate.flushed) || !read_u32(input, &offset, &sample_width) || !read_u32(input, &offset, &sample_height) || !read_bool(input, &offset, &candidate.previous_metrics.has_previous) || !read_i32(input, &offset, &candidate.previous_metrics.mean_luma_q) || !read_i32(input, &offset, &candidate.previous_metrics.delta_luma_q) || !read_i32(input, &offset, &candidate.previous_metrics.delta_hue_q) || !read_i32(input, &offset, &candidate.previous_metrics.delta_saturation_q) || !read_i32(input, &offset, &candidate.previous_metrics.content_score_q) || !read_bytes(input, &offset, &candidate.previous_metrics.luma_plane) || !read_bytes(input, &offset, &candidate.previous_metrics.hue_plane) || !read_bytes(input, &offset, &candidate.previous_metrics.saturation_plane) || !read_bool(input, &offset, &candidate.content.has_event) || !read_i64(input, &offset, &candidate.content.last_event_timestamp_us) || !read_u32(input, &offset, &window_size) || window_size > 120) { *error = ErrorCode::InvalidCheckpoint; return false; }
  candidate.previous_metrics.sample_width = sample_width; candidate.previous_metrics.sample_height = sample_height;
  if (candidate.previous_metrics.luma_plane.size() != candidate.previous_metrics.hue_plane.size() || candidate.previous_metrics.luma_plane.size() != candidate.previous_metrics.saturation_plane.size()) { *error = ErrorCode::InvalidCheckpoint; return false; }
  candidate.adaptive.window.resize(window_size);
  for (auto& entry : candidate.adaptive.window) { if (!read_i32(input, &offset, &entry.score_q) || !read_i64(input, &offset, &entry.timestamp_us) || !read_u64(input, &offset, &entry.presentation_index) || !read_i32(input, &offset, &entry.delta_luma_q) || !read_i32(input, &offset, &entry.delta_hue_q) || !read_i32(input, &offset, &entry.delta_saturation_q)) { *error = ErrorCode::InvalidCheckpoint; return false; } }
  if (!read_u64(input, &offset, &candidate.adaptive.last_emitted_index) || !read_bool(input, &offset, &candidate.adaptive.has_emitted) || !read_i64(input, &offset, &candidate.adaptive.last_event_timestamp_us) || !read_bool(input, &offset, &candidate.threshold.processed) || !read_bool(input, &offset, &candidate.threshold.fade_out) || !read_i64(input, &offset, &candidate.threshold.fade_start_us) || !read_u64(input, &offset, &candidate.threshold.fade_start_index) || !read_i64(input, &offset, &candidate.threshold.last_scene_cut_us) || !read_i64(input, &offset, &candidate.threshold.last_timestamp_us) || !read_u32(input, &offset, &history_size) || history_size > 1'000'000 || !read_u64(input, &offset, &candidate.delivered_event_count)) { *error = ErrorCode::InvalidCheckpoint; return false; }
  candidate.resolved_history.resize(history_size);
  for (auto& resolved : candidate.resolved_history) { if (!read_event(input, &offset, &resolved.event) || !read_u32(input, &offset, &resolved.source_mask)) { *error = ErrorCode::InvalidCheckpoint; return false; } }
  if (candidate.delivered_event_count > candidate.resolved_history.size() || offset != input.size() || candidate.schema_version != 1 || candidate.engine_state_version != expected_engine_state_version || candidate.config_hash != expected_config_hash) { *error = ErrorCode::InvalidCheckpoint; return false; }
  *output = candidate; *error = ErrorCode::None; return true;
}

}  // namespace aisenshot
