import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import SurfaceCard from "../../../components/ui/surface-card";
import { getCurrentSession, updatePassword } from "../../../services/auth/auth";

export default function PasswordResetPage() {
  const [password, setPassword] = useState(""); const [passwordConfirmation, setPasswordConfirmation] = useState(""); const [isCheckingSession, setIsCheckingSession] = useState(true); const [isSubmitting, setIsSubmitting] = useState(false); const [errorMessage, setErrorMessage] = useState(""); const [isComplete, setIsComplete] = useState(false);
  useEffect(() => { void getCurrentSession().then((session) => { if (!session) setErrorMessage("重置链接无效或已过期，请重新申请密码重置邮件。"); }).catch(() => setErrorMessage("无法验证重置链接，请重新申请密码重置邮件。")).finally(() => setIsCheckingSession(false)); }, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (password.length < 8) { setErrorMessage("密码至少需要 8 个字符。"); return; } if (password !== passwordConfirmation) { setErrorMessage("两次输入的密码不一致。"); return; } setIsSubmitting(true); setErrorMessage(""); try { await updatePassword(password); setIsComplete(true); toast.success("密码已更新，即将返回 AisenLens。"); window.setTimeout(() => window.location.replace("/"), 1200); } catch (error) { setErrorMessage(error instanceof Error ? error.message : "密码更新失败，请重新申请重置邮件。"); } finally { setIsSubmitting(false); } };
  return <main className="flex min-h-screen items-center justify-center bg-bg px-4 text-text-base"><SurfaceCard className="w-full max-w-md overflow-hidden border-border-mid shadow-2xl"><div className="border-b border-border px-7 py-7"><p className="font-mono text-xs tracking-widest text-accent">AISENLENS</p><h1 className="mt-1 font-display text-3xl font-black text-white">设置新密码</h1><p className="mt-1 text-sm text-text-muted">请输入至少 8 位的新密码。</p></div><form onSubmit={submit} className="flex flex-col gap-4 p-7"><div><label htmlFor="reset-password" className="mb-1.5 block font-mono text-xs tracking-wider text-text-muted">新密码</label><Input id="reset-password" value={password} onChange={(event) => { setPassword(event.target.value); setErrorMessage(""); }} type="password" autoComplete="new-password" disabled={isCheckingSession || isComplete} className="h-11 rounded-xl border-border bg-bg-input px-4 text-white" /></div><div><label htmlFor="reset-password-confirmation" className="mb-1.5 block font-mono text-xs tracking-wider text-text-muted">确认新密码</label><Input id="reset-password-confirmation" value={passwordConfirmation} onChange={(event) => { setPasswordConfirmation(event.target.value); setErrorMessage(""); }} type="password" autoComplete="new-password" disabled={isCheckingSession || isComplete} className="h-11 rounded-xl border-border bg-bg-input px-4 text-white" /></div>{errorMessage && <p role="alert" className="rounded-lg border border-red-500/20 bg-red-500/5 px-3 py-2 text-xs text-red-300">{errorMessage}</p>}{isComplete && <p className="rounded-lg border border-green-500/20 bg-green-500/5 px-3 py-2 text-xs text-green-300">密码已更新，正在返回 AisenLens…</p>}<Button type="submit" disabled={isCheckingSession || isSubmitting || isComplete} className="mt-1 h-11 w-full rounded-xl bg-accent text-white hover:bg-accent/90">{isCheckingSession ? "正在验证链接…" : isSubmitting ? "正在更新…" : "更新密码"}</Button><Button type="button" variant="link" onClick={() => window.location.replace("/")} className="text-text-muted hover:text-text-dim">返回登录</Button></form></SurfaceCard></main>;
}
